<a href="https://colab.research.google.com/github/DimiGretsistas/lab-neural-networks/blob/master/challenge_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [40]:
#imports
import pandas as pd
import numpy as np
import tensorflow as tf

#inspection of data
data = pd.read_csv("/tic-tac-toe.csv")
data.shape
data.columns
data.sample(10)
data.dtypes
data.isnull().sum()
data.nunique()
data.iloc[:, -1].value_counts()
data.duplicated().sum()
data.sample(5)

    TL TM TR ML MM MR BL BM BR  class
639  x  x  o  x  b  o  b  b  o  False
597  b  b  x  o  o  x  x  o  x   True
286  x  b  b  o  x  x  o  o  x   True
490  b  x  x  o  o  x  o  b  x   True
218  x  o  b  b  x  o  o  x  x   True

In [41]:
#from google.colab import drive
#drive.mount('/content/drive')

In [42]:
#converting  object data to numeric values
data = data.replace({"x": 1, "o": -1, "b": 0, True: 1, False: 0})
data.sample(10)

/tmp/ipykernel_1400/934364746.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data = data.replace({"x": 1, "o": -1, "b": 0, True: 1, False: 0})

     TL  TM  TR  ML  MM  MR  BL  BM  BR  class
717   1   0  -1   1   1  -1  -1   1  -1      0
402  -1  -1   1   0  -1   1   0   1   1      1
662   1   1   0   1   0   0  -1  -1  -1      0
362  -1   1   0   0   1   0  -1   1   0      1
932   0   0   1  -1  -1  -1   0   1   1      0
929   0   0   1   1   0   1  -1  -1  -1      0
484   0   1   1  -1   1  -1   1  -1   0      1
631   1   1  -1   1  -1  -1  -1   1   0      0
253   1   0  -1   1  -1   0   1   0   0      1
504   0   1  -1  -1   1  -1   0   1   1      1

In [43]:
#Separate input and output
X = data.drop("class", axis=1)
y = data["class"]

#Apply MinMax Scaler for normalization of data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X[:10]

array([[1. , 1. , 1. , 1. , 0. , 0. , 1. , 0. , 0. ],
       [1. , 1. , 1. , 1. , 0. , 0. , 0. , 1. , 0. ],
       [1. , 1. , 1. , 1. , 0. , 0. , 0. , 0. , 1. ],
       [1. , 1. , 1. , 1. , 0. , 0. , 0. , 0.5, 0.5],
       [1. , 1. , 1. , 1. , 0. , 0. , 0.5, 0. , 0.5],
       [1. , 1. , 1. , 1. , 0. , 0. , 0.5, 0.5, 0. ],
       [1. , 1. , 1. , 1. , 0. , 0.5, 0. , 0. , 0.5],
       [1. , 1. , 1. , 1. , 0. , 0.5, 0. , 0.5, 0. ],
       [1. , 1. , 1. , 1. , 0. , 0.5, 0.5, 0. , 0. ],
       [1. , 1. , 1. , 1. , 0.5, 0. , 0. , 0. , 0.5]])

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [58]:
#Split the data
from numpy.random import RandomState
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state=42)

#Create Sequential model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()

#Add layers
model.add(tf.keras.Input(shape=(X_train.shape[1],)))

model.add(Dense(16, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(2, activation="softmax"))

#Compile  & fit model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
model.fit(X_train, y_train, epochs=100, verbose=2)

#Evaluate Model
loss, accuracy = model.evaluate(X_test, y_test)

print("Loss:", loss)
print("Accuracy:", accuracy)

#Save Model
model.save("tic-tac-toe.keras")

Epoch 1/100
24/24 - 3s - 104ms/step - accuracy: 0.4569 - loss: 0.7020
Epoch 2/100
24/24 - 0s - 4ms/step - accuracy: 0.6423 - loss: 0.6699
Epoch 3/100
24/24 - 0s - 4ms/step - accuracy: 0.6658 - loss: 0.6496
Epoch 4/100
24/24 - 0s - 4ms/step - accuracy: 0.6710 - loss: 0.6319
Epoch 5/100
24/24 - 0s - 4ms/step - accuracy: 0.6736 - loss: 0.6159
Epoch 6/100
24/24 - 0s - 5ms/step - accuracy: 0.6749 - loss: 0.5998
Epoch 7/100
24/24 - 0s - 4ms/step - accuracy: 0.6945 - loss: 0.5842
Epoch 8/100
24/24 - 0s - 4ms/step - accuracy: 0.7128 - loss: 0.5698
Epoch 9/100
24/24 - 0s - 4ms/step - accuracy: 0.7337 - loss: 0.5569
Epoch 10/100
24/24 - 0s - 4ms/step - accuracy: 0.7441 - loss: 0.5441
Epoch 11/100
24/24 - 0s - 4ms/step - accuracy: 0.7585 - loss: 0.5324
Epoch 12/100
24/24 - 0s - 4ms/step - accuracy: 0.7598 - loss: 0.5235
Epoch 13/100
24/24 - 0s - 6ms/step - accuracy: 0.7663 - loss: 0.5135
Epoch 14/100
24/24 - 0s - 5ms/step - accuracy: 0.7689 - loss: 0.5069
Epoch 15/100
24/24 - 0s - 6ms/step - accuracy: 0.7689 - loss: 0.5002
Epoch 16/100
24/24 - 0s - 6ms/step - accuracy: 0.7742 - loss: 0.4944
Epoch 17/100
24/24 - 0s - 5ms/step - accuracy: 0.7755 - loss: 0.4872
Epoch 18/100
24/24 - 0s - 5ms/step - accuracy: 0.7715 - loss: 0.4822
Epoch 19/100
24/24 - 0s - 6ms/step - accuracy: 0.7833 - loss: 0.4752
Epoch 20/100
24/24 - 0s - 6ms/step - accuracy: 0.7820 - loss: 0.4693
Epoch 21/100
24/24 - 0s - 5ms/step - accuracy: 0.7833 - loss: 0.4616
Epoch 22/100
24/24 - 0s - 6ms/step - accuracy: 0.8016 - loss: 0.4547
Epoch 23/100
24/24 - 0s - 12ms/step - accuracy: 0.7977 - loss: 0.4476
Epoch 24/100
24/24 - 0s - 5ms/step - accuracy: 0.8042 - loss: 0.4416
Epoch 25/100
24/24 - 0s - 6ms/step - accuracy: 0.8120 - loss: 0.4339
Epoch 26/100
24/24 - 0s - 6ms/step - accuracy: 0.8159 - loss: 0.4268
Epoch 27/100
24/24 - 0s - 7ms/step - accuracy: 0.8211 - loss: 0.4195
Epoch 28/100
24/24 - 0s - 11ms/step - accuracy: 0.8303 - loss: 0.4124
Epoch 29/100
24/24 - 0s - 4ms/step - accuracy: 0.8211 - loss: 0.4074
Epoch 30/100
24/24 - 0s - 4ms/step - accuracy: 0.8368 - loss: 0.3989
Epoch 31/100
24/24 - 0s - 4ms/step - accuracy: 0.8473 - loss: 0.3907
Epoch 32/100
24/24 - 0s - 4ms/step - accuracy: 0.8655 - loss: 0.3819
Epoch 33/100
24/24 - 0s - 4ms/step - accuracy: 0.8655 - loss: 0.3749
Epoch 34/100
24/24 - 0s - 4ms/step - accuracy: 0.8655 - loss: 0.3679
Epoch 35/100
24/24 - 0s - 4ms/step - accuracy: 0.8812 - loss: 0.3595
Epoch 36/100
24/24 - 0s - 4ms/step - accuracy: 0.8786 - loss: 0.3528
Epoch 37/100
24/24 - 0s - 5ms/step - accuracy: 0.8812 - loss: 0.3456
Epoch 38/100
24/24 - 0s - 4ms/step - accuracy: 0.8825 - loss: 0.3367
Epoch 39/100
24/24 - 0s - 4ms/step - accuracy: 0.8838 - loss: 0.3305
Epoch 40/100
24/24 - 0s - 4ms/step - accuracy: 0.8943 - loss: 0.3234
Epoch 41/100
24/24 - 0s - 4ms/step - accuracy: 0.8995 - loss: 0.3168
Epoch 42/100
24/24 - 0s - 4ms/step - accuracy: 0.8969 - loss: 0.3123
Epoch 43/100
24/24 - 0s - 4ms/step - accuracy: 0.8982 - loss: 0.3039
Epoch 44/100
24/24 - 0s - 4ms/step - accuracy: 0.9021 - loss: 0.2984
Epoch 45/100
24/24 - 0s - 4ms/step - accuracy: 0.9021 - loss: 0.2926
Epoch 46/100
24/24 - 0s - 4ms/step - accuracy: 0.9047 - loss: 0.2857
Epoch 47/100
24/24 - 0s - 5ms/step - accuracy: 0.9138 - loss: 0.2789
Epoch 48/100
24/24 - 0s - 4ms/step - accuracy: 0.9138 - loss: 0.2723
Epoch 49/100
24/24 - 0s - 4ms/step - accuracy: 0.9256 - loss: 0.2663
Epoch 50/100
24/24 - 0s - 4ms/step - accuracy: 0.9282 - loss: 0.2598
Epoch 51/100
24/24 - 0s - 4ms/step - accuracy: 0.9321 - loss: 0.2563
Epoch 52/100
24/24 - 0s - 4ms/step - accuracy: 0.9321 - loss: 0.2491
Epoch 53/100
24/24 - 0s - 4ms/step - accuracy: 0.9360 - loss: 0.2435
Epoch 54/100
24/24 - 0s - 4ms/step - accuracy: 0.9413 - loss: 0.2393
Epoch 55/100
24/24 - 0s - 4ms/step - accuracy: 0.9386 - loss: 0.2328
Epoch 56/100
24/24 - 0s - 4ms/step - accuracy: 0.9373 - loss: 0.2287
Epoch 57/100
24/24 - 0s - 4ms/step - accuracy: 0.9413 - loss: 0.2243
Epoch 58/100
24/24 - 0s - 4ms/step - accuracy: 0.9413 - loss: 0.2185
Epoch 59/100
24/24 - 0s - 4ms/step - accuracy: 0.9465 - loss: 0.2145
Epoch 60/100
24/24 - 0s - 4ms/step - accuracy: 0.9439 - loss: 0.2097
Epoch 61/100
24/24 - 0s - 4ms/step - accuracy: 0.9504 - loss: 0.2035
Epoch 62/100
24/24 - 0s - 4ms/step - accuracy: 0.9504 - loss: 0.1996
Epoch 63/100
24/24 - 0s - 4ms/step - accuracy: 0.9517 - loss: 0.1956
Epoch 64/100
24/24 - 0s - 4ms/step - accuracy: 0.9556 - loss: 0.1917
Epoch 65/100
24/24 - 0s - 4ms/step - accuracy: 0.9595 - loss: 0.1865
Epoch 66/100
24/24 - 0s - 4ms/step - accuracy: 0.9608 - loss: 0.1821
Epoch 67/100
24/24 - 0s - 4ms/step - accuracy: 0.9621 - loss: 0.1786
Epoch 68/100
24/24 - 0s - 5ms/step - accuracy: 0.9621 - loss: 0.1757
Epoch 69/100
24/24 - 0s - 5ms/step - accuracy: 0.9621 - loss: 0.1704
Epoch 70/100
24/24 - 0s - 4ms/step - accuracy: 0.9661 - loss: 0.1661
Epoch 71/100
24/24 - 0s - 5ms/step - accuracy: 0.9687 - loss: 0.1624
Epoch 72/100
24/24 - 0s - 4ms/step - accuracy: 0.9661 - loss: 0.1591
Epoch 73/100
24/24 - 0s - 4ms/step - accuracy: 0.9687 - loss: 0.1545
Epoch 74/100
24/24 - 0s - 4ms/step - accuracy: 0.9700 - loss: 0.1520
Epoch 75/100
24/24 - 0s - 4ms/step - accuracy: 0.9700 - loss: 0.1484
Epoch 76/100
24/24 - 0s - 4ms/step - accuracy: 0.9752 - loss: 0.1438
Epoch 77/100
24/24 - 0s - 4ms/step - accuracy: 0.9674 - loss: 0.1430
Epoch 78/100
24/24 - 0s - 4ms/step - accuracy: 0.9687 - loss: 0.1391
Epoch 79/100
24/24 - 0s - 4ms/step - accuracy: 0.9739 - loss: 0.1362
Epoch 80/100
24/24 - 0s - 4ms/step - accuracy: 0.9739 - loss: 0.1327
Epoch 81/100
24/24 - 0s - 4ms/step - accuracy: 0.9791 - loss: 0.1298
Epoch 82/100
24/24 - 0s - 4ms/step - accuracy: 0.9713 - loss: 0.1282
Epoch 83/100
24/24 - 0s - 4ms/step - accuracy: 0.9752 - loss: 0.1258
Epoch 84/100
24/24 - 0s - 4ms/step - accuracy: 0.9778 - loss: 0.1223
Epoch 85/100
24/24 - 0s - 4ms/step - accuracy: 0.9765 - loss: 0.1206
Epoch 86/100
24/24 - 0s - 4ms/step - accuracy: 0.9791 - loss: 0.1183
Epoch 87/100
24/24 - 0s - 4ms/step - accuracy: 0.9830 - loss: 0.1148
Epoch 88/100
24/24 - 0s - 5ms/step - accuracy: 0.9843 - loss: 0.1138
Epoch 89/100
24/24 - 0s - 4ms/step - accuracy: 0.9791 - loss: 0.1125
Epoch 90/100
24/24 - 0s - 4ms/step - accuracy: 0.9869 - loss: 0.1086
Epoch 91/100
24/24 - 0s - 4ms/step - accuracy: 0.9856 - loss: 0.1076
Epoch 92/100
24/24 - 0s - 4ms/step - accuracy: 0.9856 - loss: 0.1052
Epoch 93/100
24/24 - 0s - 4ms/step - accuracy: 0.9830 - loss: 0.1039
Epoch 94/100
24/24 - 0s - 4ms/step - accuracy: 0.9869 - loss: 0.1002
Epoch 95/100
24/24 - 0s - 4ms/step - accuracy: 0.9856 - loss: 0.0988
Epoch 96/100
24/24 - 0s - 4ms/step - accuracy: 0.9869 - loss: 0.0963
Epoch 97/100
24/24 - 0s - 4ms/step - accuracy: 0.9817 - loss: 0.0982
Epoch 98/100
24/24 - 0s - 4ms/step - accuracy: 0.9883 - loss: 0.0938
Epoch 99/100
24/24 - 0s - 4ms/step - accuracy: 0.9896 - loss: 0.0928
Epoch 100/100
24/24 - 0s - 4ms/step - accuracy: 0.9883 - loss: 0.0904
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9479 - loss: 0.1534
Loss: 0.15344637632369995
Accuracy: 0.9479166865348816

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [39]:
from tensorflow.keras.models import load_model
model = load_model("tic-tac-toe.keras")
idx = np.random.choice(len(X_test), 5, replace=False)

X_sample = X_test[idx]
y_true = y_test.iloc[idx]
predictions = model.predict(X_sample)
y_pred = np.argmax(predictions, axis=1)

print("True:", y_true.values)
print("Pred:", y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step
True: [1 1 0 1 1]
Pred: [1 1 0 1 1]

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [57]:
#Initiate model
model = Sequential()

#Creating the layers
model.add(tf.keras.Input(shape=(X_train.shape[1],)))

model.add(Dense(32, activation="relu"))
model.add(Dense(16, activation="relu"))
model.add(Dense(8, activation="relu"))
model.add(Dense(2, activation="softmax"))

#Adjusting learning rate
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)

#Compile model
model.compile(optimizer=optimizer, loss="sparse_categorical_crossentropy", metrics=["accuracy"])
early_stopping = tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

model.fit(X_train, y_train, epochs=80, validation_split=0.2, callbacks=[early_stopping], verbose=2)

loss, accuracy = model.evaluate(X_test, y_test)

print("Loss:", loss)
print("Accuracy", accuracy)

Epoch 1/80
20/20 - 3s - 155ms/step - accuracy: 0.5768 - loss: 0.6833 - val_accuracy: 0.6818 - val_loss: 0.6596
Epoch 2/80
20/20 - 0s - 7ms/step - accuracy: 0.6438 - loss: 0.6547 - val_accuracy: 0.6818 - val_loss: 0.6306
Epoch 3/80
20/20 - 0s - 7ms/step - accuracy: 0.6487 - loss: 0.6335 - val_accuracy: 0.6818 - val_loss: 0.6104
Epoch 4/80
20/20 - 0s - 8ms/step - accuracy: 0.6471 - loss: 0.6199 - val_accuracy: 0.6818 - val_loss: 0.5941
Epoch 5/80
20/20 - 0s - 7ms/step - accuracy: 0.6471 - loss: 0.6078 - val_accuracy: 0.6818 - val_loss: 0.5807
Epoch 6/80
20/20 - 0s - 7ms/step - accuracy: 0.6471 - loss: 0.5948 - val_accuracy: 0.6818 - val_loss: 0.5742
Epoch 7/80
20/20 - 0s - 7ms/step - accuracy: 0.6471 - loss: 0.5814 - val_accuracy: 0.6818 - val_loss: 0.5622
Epoch 8/80
20/20 - 0s - 7ms/step - accuracy: 0.6732 - loss: 0.5721 - val_accuracy: 0.7013 - val_loss: 0.5528
Epoch 9/80
20/20 - 0s - 7ms/step - accuracy: 0.6846 - loss: 0.5591 - val_accuracy: 0.7208 - val_loss: 0.5413
Epoch 10/80
20/20 - 0s - 7ms/step - accuracy: 0.7010 - loss: 0.5468 - val_accuracy: 0.7338 - val_loss: 0.5328
Epoch 11/80
20/20 - 0s - 8ms/step - accuracy: 0.7386 - loss: 0.5325 - val_accuracy: 0.7597 - val_loss: 0.5245
Epoch 12/80
20/20 - 0s - 8ms/step - accuracy: 0.7614 - loss: 0.5188 - val_accuracy: 0.7468 - val_loss: 0.5108
Epoch 13/80
20/20 - 0s - 7ms/step - accuracy: 0.7565 - loss: 0.5079 - val_accuracy: 0.7792 - val_loss: 0.5102
Epoch 14/80
20/20 - 0s - 8ms/step - accuracy: 0.7859 - loss: 0.4936 - val_accuracy: 0.7922 - val_loss: 0.4902
Epoch 15/80
20/20 - 0s - 7ms/step - accuracy: 0.7794 - loss: 0.4780 - val_accuracy: 0.7857 - val_loss: 0.4817
Epoch 16/80
20/20 - 0s - 7ms/step - accuracy: 0.8023 - loss: 0.4627 - val_accuracy: 0.7792 - val_loss: 0.4716
Epoch 17/80
20/20 - 0s - 7ms/step - accuracy: 0.7974 - loss: 0.4509 - val_accuracy: 0.7987 - val_loss: 0.4670
Epoch 18/80
20/20 - 0s - 8ms/step - accuracy: 0.7974 - loss: 0.4439 - val_accuracy: 0.7987 - val_loss: 0.4524
Epoch 19/80
20/20 - 0s - 7ms/step - accuracy: 0.8088 - loss: 0.4307 - val_accuracy: 0.8052 - val_loss: 0.4508
Epoch 20/80
20/20 - 0s - 8ms/step - accuracy: 0.8170 - loss: 0.4147 - val_accuracy: 0.8117 - val_loss: 0.4366
Epoch 21/80
20/20 - 0s - 7ms/step - accuracy: 0.8252 - loss: 0.4036 - val_accuracy: 0.8052 - val_loss: 0.4284
Epoch 22/80
20/20 - 0s - 7ms/step - accuracy: 0.8431 - loss: 0.3888 - val_accuracy: 0.8052 - val_loss: 0.4195
Epoch 23/80
20/20 - 0s - 7ms/step - accuracy: 0.8480 - loss: 0.3778 - val_accuracy: 0.8182 - val_loss: 0.4071
Epoch 24/80
20/20 - 0s - 7ms/step - accuracy: 0.8415 - loss: 0.3644 - val_accuracy: 0.8182 - val_loss: 0.4043
Epoch 25/80
20/20 - 0s - 8ms/step - accuracy: 0.8742 - loss: 0.3513 - val_accuracy: 0.8377 - val_loss: 0.3863
Epoch 26/80
20/20 - 0s - 7ms/step - accuracy: 0.8676 - loss: 0.3389 - val_accuracy: 0.8377 - val_loss: 0.3781
Epoch 27/80
20/20 - 0s - 7ms/step - accuracy: 0.8856 - loss: 0.3250 - val_accuracy: 0.8571 - val_loss: 0.3689
Epoch 28/80
20/20 - 0s - 7ms/step - accuracy: 0.8775 - loss: 0.3162 - val_accuracy: 0.8442 - val_loss: 0.3591
Epoch 29/80
20/20 - 0s - 7ms/step - accuracy: 0.8922 - loss: 0.3003 - val_accuracy: 0.8701 - val_loss: 0.3522
Epoch 30/80
20/20 - 0s - 7ms/step - accuracy: 0.9003 - loss: 0.2936 - val_accuracy: 0.8701 - val_loss: 0.3453
Epoch 31/80
20/20 - 0s - 7ms/step - accuracy: 0.9265 - loss: 0.2779 - val_accuracy: 0.8766 - val_loss: 0.3305
Epoch 32/80
20/20 - 0s - 9ms/step - accuracy: 0.9232 - loss: 0.2671 - val_accuracy: 0.8766 - val_loss: 0.3258
Epoch 33/80
20/20 - 0s - 11ms/step - accuracy: 0.9265 - loss: 0.2571 - val_accuracy: 0.8636 - val_loss: 0.3083
Epoch 34/80
20/20 - 0s - 11ms/step - accuracy: 0.9281 - loss: 0.2446 - val_accuracy: 0.8766 - val_loss: 0.3072
Epoch 35/80
20/20 - 0s - 10ms/step - accuracy: 0.9461 - loss: 0.2352 - val_accuracy: 0.8896 - val_loss: 0.2981
Epoch 36/80
20/20 - 0s - 9ms/step - accuracy: 0.9510 - loss: 0.2233 - val_accuracy: 0.8701 - val_loss: 0.2869
Epoch 37/80
20/20 - 0s - 12ms/step - accuracy: 0.9412 - loss: 0.2226 - val_accuracy: 0.9091 - val_loss: 0.2805
Epoch 38/80
20/20 - 0s - 10ms/step - accuracy: 0.9592 - loss: 0.2081 - val_accuracy: 0.9091 - val_loss: 0.2757
Epoch 39/80
20/20 - 0s - 9ms/step - accuracy: 0.9559 - loss: 0.2000 - val_accuracy: 0.8961 - val_loss: 0.2652
Epoch 40/80
20/20 - 0s - 10ms/step - accuracy: 0.9559 - loss: 0.1902 - val_accuracy: 0.9026 - val_loss: 0.2545
Epoch 41/80
20/20 - 0s - 10ms/step - accuracy: 0.9673 - loss: 0.1822 - val_accuracy: 0.8961 - val_loss: 0.2445
Epoch 42/80
20/20 - 0s - 16ms/step - accuracy: 0.9575 - loss: 0.1739 - val_accuracy: 0.9156 - val_loss: 0.2457
Epoch 43/80
20/20 - 0s - 8ms/step - accuracy: 0.9706 - loss: 0.1631 - val_accuracy: 0.9026 - val_loss: 0.2513
Epoch 44/80
20/20 - 0s - 7ms/step - accuracy: 0.9690 - loss: 0.1631 - val_accuracy: 0.9221 - val_loss: 0.2194
Epoch 45/80
20/20 - 0s - 7ms/step - accuracy: 0.9755 - loss: 0.1514 - val_accuracy: 0.9286 - val_loss: 0.2165
Epoch 46/80
20/20 - 0s - 7ms/step - accuracy: 0.9771 - loss: 0.1441 - val_accuracy: 0.9221 - val_loss: 0.2082
Epoch 47/80
20/20 - 0s - 7ms/step - accuracy: 0.9673 - loss: 0.1460 - val_accuracy: 0.9221 - val_loss: 0.2062
Epoch 48/80
20/20 - 0s - 7ms/step - accuracy: 0.9739 - loss: 0.1325 - val_accuracy: 0.9026 - val_loss: 0.2218
Epoch 49/80
20/20 - 0s - 7ms/step - accuracy: 0.9804 - loss: 0.1280 - val_accuracy: 0.9351 - val_loss: 0.1934
Epoch 50/80
20/20 - 0s - 7ms/step - accuracy: 0.9853 - loss: 0.1181 - val_accuracy: 0.9286 - val_loss: 0.1892
Epoch 51/80
20/20 - 0s - 7ms/step - accuracy: 0.9837 - loss: 0.1166 - val_accuracy: 0.9286 - val_loss: 0.1843
Epoch 52/80
20/20 - 0s - 7ms/step - accuracy: 0.9837 - loss: 0.1142 - val_accuracy: 0.9351 - val_loss: 0.1724
Epoch 53/80
20/20 - 0s - 7ms/step - accuracy: 0.9886 - loss: 0.1063 - val_accuracy: 0.9416 - val_loss: 0.1607
Epoch 54/80
20/20 - 0s - 7ms/step - accuracy: 0.9902 - loss: 0.0988 - val_accuracy: 0.9351 - val_loss: 0.1655
Epoch 55/80
20/20 - 0s - 8ms/step - accuracy: 0.9918 - loss: 0.0925 - val_accuracy: 0.9286 - val_loss: 0.1587
Epoch 56/80
20/20 - 0s - 7ms/step - accuracy: 0.9902 - loss: 0.0862 - val_accuracy: 0.9351 - val_loss: 0.1697
Epoch 57/80
20/20 - 0s - 7ms/step - accuracy: 0.9918 - loss: 0.0859 - val_accuracy: 0.9351 - val_loss: 0.1587
Epoch 58/80
20/20 - 0s - 7ms/step - accuracy: 0.9918 - loss: 0.0805 - val_accuracy: 0.9416 - val_loss: 0.1443
Epoch 59/80
20/20 - 0s - 7ms/step - accuracy: 0.9918 - loss: 0.0785 - val_accuracy: 0.9416 - val_loss: 0.1386
Epoch 60/80
20/20 - 0s - 7ms/step - accuracy: 0.9869 - loss: 0.0779 - val_accuracy: 0.9416 - val_loss: 0.1422
Epoch 61/80
20/20 - 0s - 8ms/step - accuracy: 0.9935 - loss: 0.0759 - val_accuracy: 0.9481 - val_loss: 0.1308
Epoch 62/80
20/20 - 0s - 9ms/step - accuracy: 0.9902 - loss: 0.0720 - val_accuracy: 0.9351 - val_loss: 0.1315
Epoch 63/80
20/20 - 0s - 7ms/step - accuracy: 0.9935 - loss: 0.0667 - val_accuracy: 0.9610 - val_loss: 0.1202
Epoch 64/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0617 - val_accuracy: 0.9481 - val_loss: 0.1333
Epoch 65/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0557 - val_accuracy: 0.9481 - val_loss: 0.1201
Epoch 66/80
20/20 - 0s - 7ms/step - accuracy: 0.9935 - loss: 0.0548 - val_accuracy: 0.9481 - val_loss: 0.1318
Epoch 67/80
20/20 - 0s - 8ms/step - accuracy: 0.9902 - loss: 0.0594 - val_accuracy: 0.9351 - val_loss: 0.1190
Epoch 68/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0530 - val_accuracy: 0.9481 - val_loss: 0.1079
Epoch 69/80
20/20 - 0s - 8ms/step - accuracy: 0.9951 - loss: 0.0479 - val_accuracy: 0.9610 - val_loss: 0.1122
Epoch 70/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0462 - val_accuracy: 0.9610 - val_loss: 0.1022
Epoch 71/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0425 - val_accuracy: 0.9610 - val_loss: 0.1068
Epoch 72/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0415 - val_accuracy: 0.9610 - val_loss: 0.1049
Epoch 73/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0391 - val_accuracy: 0.9675 - val_loss: 0.0989
Epoch 74/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0385 - val_accuracy: 0.9740 - val_loss: 0.0954
Epoch 75/80
20/20 - 0s - 8ms/step - accuracy: 0.9951 - loss: 0.0356 - val_accuracy: 0.9610 - val_loss: 0.0977
Epoch 76/80
20/20 - 0s - 8ms/step - accuracy: 0.9967 - loss: 0.0338 - val_accuracy: 0.9610 - val_loss: 0.0950
Epoch 77/80
20/20 - 0s - 7ms/step - accuracy: 0.9951 - loss: 0.0326 - val_accuracy: 0.9675 - val_loss: 0.0959
Epoch 78/80
20/20 - 0s - 7ms/step - accuracy: 0.9984 - loss: 0.0321 - val_accuracy: 0.9545 - val_loss: 0.0916
Epoch 79/80
20/20 - 0s - 8ms/step - accuracy: 0.9951 - loss: 0.0311 - val_accuracy: 0.9675 - val_loss: 0.0901
Epoch 80/80
20/20 - 0s - 7ms/step - accuracy: 1.0000 - loss: 0.0290 - val_accuracy: 0.9675 - val_loss: 0.0844
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9740 - loss: 0.1165
Loss: 0.11654561012983322
Accuracy 0.9739583134651184

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here